### PR TITLE
Add module python win32crypt in windows11

### PR DESCRIPTION
**Pull request by VuDn5**
Dear @dkmstr 
This merge to hot fix bug: "Module win32crypt not found" 
Link issues:  https://github.com/VirtualCable/uds-client/issues/2 
Thanks for review

### CODE REVIEW

**Comment by dkmstr** [comment]
It's better to include it on builders (pyinstaller .spec, etc..) that pushing it into the source...

Thanks for your support anyway!!! ;-)

**Comment by VuDn5** [comment]
> It's better to include it on builders (pyinstaller .spec, etc..) that pushing it into the source...
> 
> Thanks for your support anyway!!! ;-)

Dear @dkmstr 
"Thank you for your response. Do we need to commit the .spec file to support PyInstaller and include a README to guide users in building the USDClient?"

**Comment by dkmstr** [comment]
Maybe an explanation or a "sample .spec" for pyinstaller maybe fine... :)
Thats a good point of help for anyone, and unfortunately, i lack the time i need to document everything as it should :(
So yes, it's a good idea to create, for example, a folder at root level called "pyinstaller" (or something like it), with a sample .spec file for Windows, maybe Mac also?, and a readme. It should help a lot others i think

So thank you very much for your interest and help!
Regards,

**Comment by VuDn5** [comment]
> Maybe an explanation or a "sample .spec" for pyinstaller maybe fine... :) Thats a good point of help for anyone, and unfortunately, i lack the time i need to document everything as it should :( So yes, it's a good idea to create, for example, a folder at root level called "pyinstaller" (or something like it), with a sample .spec file for Windows, maybe Mac also?, and a readme. It should help a lot others i think
> 
> So thank you very much for your interest and help! Regards,

Yes, i will. 
^-^

**Comment by dkmstr** [comment]
Thank you! ;-)

**Pull request closed without merging**
